<?php

/**
 * @file
 * Provides integration with 3rd party modules and the jCarousel library.
 */
use Drupal\Core\Asset;
use Drupal\jcarousel;
use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function jcarousel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.jcarousel':
      $details = [
        '#type' => 'details',
        '#title' => t('View sample code'),
        '#description' => t('The following HTML may be printed out to the page through a node, block, or in a custom template. Then the following PHP code must be run to add the jCarousel library and CSS to the page.'),
      ];

      $output = '';

      $output .= '<p>' . t('The jCarousel module provides the ability to create carousel-style lists such as those included on this page. The jCarousel module includes integrations with other Drupal modules, but may also be used manually within your own theme or custom modules. It does not include any site-wide settings page or options, each carousel is separately configured.') . '</p>';

      $output .= '<h2>' . t('Views integration') . '</h2>';
      $output .= '<p>';
      $output .= t('Most configuration options for the jCarousel module are provided through <a href=":views">Views module</a>.', [
          ':views' => \Drupal::moduleHandler()
            ->moduleExists('views') ? \Drupal::url('help.page', ['name' => 'views']) : '#'
        ]
      );
      if (\Drupal::moduleHandler()->moduleExists('views_ui')) {
        $output .= ' ' . t('You may configure a new view through the <a href=":views-url">Views module interface</a>. After adding a new view, change its "Display style" to "jCarousel" and configure the remaining options there. When using the jCarousel display style with Views, you can construct any of the examples on this page as well as dynamically loaded carousels through AJAX requests.', [
            ':views-url' => \Drupal::url('entity.view.collection'),
          ]);
      }
      elseif (\Drupal::moduleHandler()->moduleExists('views')) {
        $output .= ' ' . t('This site not have Views (or the Views UI module) installed currently. You may be able to turn on this module under your site\'s <a href="!modules-url">module page</a>, or you may have to <a href=":module">download Views module</a> and install it.', [
            ':modules-url' => \Drupal::url('system.modules_list'),
          ]);
      }
      $output .= '</p>';

      $output .= '<h2>' . t('Custom implementations') . '</h2>';
      $output .= '<p>' . t('The following are demonstrations of jCarousel module when used directly by another module or your theme. <strong>Most users do not need to manually code carousels</strong> (building carousels using Views is the most common approach), but these demonstrations provide good examples of jCarousel\'s abilities.') . '</p>';

      // Construct the jCarousel list.
      $list = '
  <li><img src="http://static.flickr.com/66/199481236_dc98b5abb3_s.jpg" width="75" height="75" alt="" /></li>
  <li><img src="http://static.flickr.com/75/199481072_b4a0d09597_s.jpg" width="75" height="75" alt="" /></li>
  <li><img src="http://static.flickr.com/57/199481087_33ae73a8de_s.jpg" width="75" height="75" alt="" /></li>
  <li><img src="http://static.flickr.com/77/199481108_4359e6b971_s.jpg" width="75" height="75" alt="" /></li>
  <li><img src="http://static.flickr.com/58/199481143_3c148d9dd3_s.jpg" width="75" height="75" alt="" /></li>
  <li><img src="http://static.flickr.com/72/199481203_ad4cdcf109_s.jpg" width="75" height="75" alt="" /></li>
  <li><img src="http://static.flickr.com/58/199481218_264ce20da0_s.jpg" width="75" height="75" alt="" /></li>
  <li><img src="http://static.flickr.com/69/199481255_fdfe885f87_s.jpg" width="75" height="75" alt="" /></li>
  <li><img src="http://static.flickr.com/60/199480111_87d4cb3e38_s.jpg" width="75" height="75" alt="" /></li>
  <li><img src="http://static.flickr.com/70/229228324_08223b70fa_s.jpg" width="75" height="75" alt="" /></li>
';

      // Provide the horizontal carousel demonstration.
      $output .= '<h3>' . t('Horizontal carousel') . '</h3>';
      $output .= '<p>' . t('This example uses <code>jcarousel_add()</code> directly with no options to create the default horizontal carousel.') . '</p>';
      $list_html = '<ul class="horizontalcarousel jcarousel-skin-default">' . $list . '</ul>';

      $sample = $details;
      $sample['sample'] = [
        '#type' => 'inline_template',
        '#template' => '<code><pre>{{ list_html }}</pre></code> {{ php_code|raw }}',
        '#context' => [
          'list_html' => $list_html,
          'php_code' => highlight_string("<?php jcarousel_add('horizontalcarousel'); ?>", TRUE),
        ]
      ];
      $output .= drupal_render($sample);

      $output .= $list_html;
      jcarousel_add('horizontalcarousel');


      // Provide the vertical carousel demonstration.
      $output .= '<h3>' . t('Vertical carousel') . '</h3>';
      $output .= '<p>' . t('jCarousel can accept a variety of <a href=":url">configuration options</a> via the second argument to <code>jcarousel_add()</code>. In this example, we created a vertical carousel.', [
          ':url' => 'http://sorgalla.com/projects/jcarousel/#Configuration',
        ]) . '</p>';
      $list_html = '<ul class="verticalcarousel jcarousel-skin-default">' . $list . '</ul>';

      $sample = $details;
      $sample['sample'] = [
        '#type' => 'inline_template',
        '#template' => '<code><pre>{{ list_html }}</pre></code> {{ php_code|raw }}',
        '#context' => [
          'list_html' => $list_html,
          'php_code' => highlight_string("<?php jcarousel_add('verticalcarousel', ['vertical' => TRUE]); ?>", TRUE),
        ]
      ];
      $output .= drupal_render($sample);

      $output .= $list_html;
      jcarousel_add('verticalcarousel', ['vertical' => TRUE]);

      // Provide the different skins carousel demonstration.
      $output .= '<h3>' . t('Different skins') . '</h3>';
      $list_html = '<ul class="differentskin jcarousel-skin-tango">' . $list . '</ul>';
//      $output .= '<p>' . t('The "skin" of a carousel can be changed by setting the <code>$options[\'skin\']</code> property. This skin must match one of the skins either provided by a module or matching a skin included in your theme\'s style.css file. Skins are simply a class given to the HTML list with the name "jcarousel-skin-[skin-name]". A custom skin path may be specified in <code>$options[\'skin path\']</code>, or you can use one of these module-based skins:') . theme('item_list', ['items' => array_keys(jcarousel_skins())]) . t('Note that with skins you will often need to override certain CSS styles in your theme\'s style.css file. Certain properties (like the height and width of individual items and the carousel itself) must be manually specified directly in CSS. Not using a skin at all by specifying <code>$options[\'skin\'] = NULL</code> and then styling the entire carousel in style.css is also a good approach.') . '</p>';

      $sample = $details;
      $sample['sample'] = [
        '#type' => 'inline_template',
        '#template' => '<code><pre>{{ list_html }}</pre></code> {{ php_code|raw }}',
        '#context' => [
          'list_html' => $list_html,
          'php_code' => highlight_string("<?php jcarousel_add('differentskin', ['skin' => 'tango']); ?>", TRUE),
        ]
      ];
      $output .= drupal_render($sample);

      $output .= $list_html;
      jcarousel_add('differentskin', ['skin' => 'tango']);

      // Another thing you can do is use the theme('jcarousel') function.
      $output .= '<h3>' . t('Theme function') . '</h3>';
//      $output .= '<p>' . t('The <code>theme(\'jcarousel\')</code> function allows you to easily create the markup and add all the JavaScript to the page in one function call. Like <code>jcarousel_add()</code> the theme function approach can also take options. In this example we create the carousel with the button next event being called when the mouse rolls over the buttons.') . '</p>';
      $items = [
        '<img src="http://static.flickr.com/66/199481236_dc98b5abb3_s.jpg" width="75" height="75" alt="" />',
        '<img src="http://static.flickr.com/75/199481072_b4a0d09597_s.jpg" width="75" height="75" alt="" />',
        '<img src="http://static.flickr.com/57/199481087_33ae73a8de_s.jpg" width="75" height="75" alt="" />',
        '<img src="http://static.flickr.com/77/199481108_4359e6b971_s.jpg" width="75" height="75" alt="" />',
        '<img src="http://static.flickr.com/58/199481143_3c148d9dd3_s.jpg" width="75" height="75" alt="" />',
        '<img src="http://static.flickr.com/72/199481203_ad4cdcf109_s.jpg" width="75" height="75" alt="" />',
        '<img src="http://static.flickr.com/58/199481218_264ce20da0_s.jpg" width="75" height="75" alt="" />',
        '<img src="http://static.flickr.com/69/199481255_fdfe885f87_s.jpg" width="75" height="75" alt="" />',
        '<img src="http://static.flickr.com/60/199480111_87d4cb3e38_s.jpg" width="75" height="75" alt="" />',
        '<img src="http://static.flickr.com/70/229228324_08223b70fa_s.jpg" width="75" height="75" alt="" />',
      ];
      $options = [
        'buttonNextEvent' => 'mouseover',
        'buttonPrevEvent' => 'mouseover',
      ];
      $details['#description'] = t('The following PHP code may be placed in a template file or a module to create a carousel.');

      $sample = $details;
      $sample['sample'] = [
        '#type' => 'inline_template',
        '#template' => '{{ php_code|raw }}',
        '#context' => [
          'php_code' => highlight_string("<?php\n\$items = " . var_export($items, TRUE) . ";\n\$options = " . var_export($options, TRUE) . ";\nprint theme('jcarousel', ['items' => \$items, 'options' => \$options]);\n?>", TRUE),
        ]
      ];
      $output .= drupal_render($sample);
      $example = [
        '#theme' => 'jcarousel',
        '#items' => $items,
        '#options' => $options,
      ];
      $output .= drupal_render($example);

      // Provide a circular wrap element.
      $output .= '<h3>' . t('Circular wrap') . '</h3>';
      $output .= '<p>' . t('This example puts the carousel into a circular wrap.') . '</p>';

      $options = [
        'wrap' => 'circular',
      ];
      $sample = $details;
      $sample['sample'] = [
        '#type' => 'inline_template',
        '#template' => '{{ php_code|raw }}',
        '#context' => [
          'php_code' => highlight_string("<?php\n\$items = " . var_export($items, TRUE) . ";\n\$options = " . var_export($options, TRUE) . ";\nprint theme('jcarousel', ['items' => \$items, 'options' => \$options]);\n ", TRUE),
        ]
      ];
      $output .= drupal_render($sample);
      $example = [
        '#theme' => 'jcarousel',
        '#items' => $items,
        '#options' => $options,
      ];
      $output .= drupal_render($example);

      return $output;
  }
}

/**
 * Implements hook_menu().
 */
//function jcarousel_menu() {
//  $items['jcarousel/ajax/views'] = array(
//    'page callback' => 'jcarousel_views_ajax',
//    'access callback' => TRUE,
//    'file' => 'includes/jcarousel.views.inc',
//    'type' => MENU_CALLBACK,
//  );
//  return $items;
//}

/**
 * Implementation of hook_init().
 */
//function jcarousel_init() {
// Global JS settings required for all carousels.
//  drupal_add_js(array('jcarousel' => array('ajaxPath' => url('jcarousel/ajax/views'))), 'setting');
//}

/**
 * Implements hook_theme().
 */
function jcarousel_theme() {
  return [
    'jcarousel' => [
      'variables' => [
        'items' => [],
        'options' => [],
        'identifier' => NULL,
      ],
//      'function' => 'theme_jcarousel',
    ],
  ];
}

/**
 * Adds all the necessary CSS and JS necessary for building a carousel.
 *
 * @param $class_name
 *   (optional) The class on the UL list to identify this carousel. If ommitted,
 *   only the jCarousel library will be added to the page.
 * @param $options
 *   (optional) A list of settings to be passed to jCarousel.
 * @param $add
 *   Whether to add the JavaScript and CSS to the page with drupal_add_js().
 * @return
 *   An array of JS and CSS files, suitable for inclusion as an #attached array.
 */
function jcarousel_add($class_name = NULL, $options = array(), $add = TRUE) {
  static $library_added;

  // Add the jCarousel library and any global settings.
  $attachments['library'][] = 'jcarousel/jcarousel';

  if (isset($class_name)) {
    // Set default options.
    $options += array(
      'skin' => 'default',
      'selector' => '.' . $class_name,
    );
    if (!empty($options['skin'])) {
      $attachments['library'][] = 'jcarousel/skin.' . $options['skin'];
    }

    // Allow other modules to modify these settings.
    \Drupal::moduleHandler()->alter('jcarousel_options', $options, $class_name);

    // Add settings for this individual carousel.
    if (!isset($library_added[$class_name]) || !$add) {
      $library_added[$class_name] = TRUE;

      // Add the JavaScript settings for this carousel.
      $js_settings = array(
        'jcarousel' => array(
          'carousels' => array(
            $class_name => $options,
          ),
        ),
      );

      $attachments['drupalSettings'] = $js_settings;
    }
  }

  return $attachments;
}

/**
 * Returns a list of all available jCarousel skins.
 *
 * @return array
 *   Keyed array of skins.
 */
function jcarousel_skins() {
  return \Drupal::service('jcarousel.skins.manager')->getDefinitions();
}

/**
 * Creates a jCarousel element on the page.
 *
 * @param $items
 *   The items to appear in the carousel.
 * @param $options
 *   The arguments to apply to the selected element when creating the jCarousel.
 *   The arguments are passed through as an associative array using the
 *   jCarousel configuration options:
 *   http://sorgalla.com/projects/jcarousel/#Configuration
 *
 *   The special option "skin" may also be specified to use any skin provided
 *   by jcarousel_skins() and hook_jcarousel_skin_info().
 * @param $id
 *   An ID for this carousel. If not provided, one will be generated
 *   automatically. Note that this is not the "id" attribute on the HTML list,
 *   instead it is one of the classes added to the UL tag.
 */
//function theme_jcarousel($variables) {
//  $items = $variables['items'];
//  $options = $variables['options'];
//  $identifier = $variables['identifier'];
//  static $unique;
//
//  if (!isset($identifier)) {
//    $unique = isset($unique) ? $unique + 1 : 1;
//    $identifier = 'jcarousel-id-' . $unique;
//  }
//
//  $options['skin'] = array_key_exists('skin', $options) ? $options['skin'] : 'default';
//  jcarousel_add($identifier, $options);
//
//  $classes = 'jcarousel ' . $identifier;
//  if (!empty($options['skin'])) {
//    $classes .= ' jcarousel-skin-' . $options['skin'];
//  }
//
//  $output = '<ul class="' . $classes . '">';
//  if (is_array($items)) {
//    foreach ($items as $item) {
//      $output .= '<li>' . $item . '</li>';
//    }
//  }
//  $output .= '</ul>';
//  return $output;
//}

/**
 * Implements hook_library_info_alter().
 *
 * Add skins as libraries.
 */
function jcarousel_library_info_alter(&$libraries, $extension) {
  if ($extension == 'jcarousel') {
    $skins = \Drupal::service('jcarousel.skins.manager')->getDefinitions();
    foreach ($skins as $key => $data) {
      $libraries["skin.$key"] = [
        'version' => 'VERSION',
        'css' => [
          'theme' => [
            $data['file'] => [],
          ],
        ],
      ];
    }
  }
}
